### ISSUE TITLE
dx find data --tag does not find tagged jobs

### ISSUE THREAD

**Issue by mjmonroe** [dnanexus/dx-toolkit#103]
To reproduce the error:
1. Tag a job
2. Run the dx find data --tag myTag

It also doesn't appear that --class will accept "job" as a class.
From the help:
--class {record,file,gtable,applet,workflow}

**Comment by psung** [comment]
Please use `dx find jobs [--tag]` to search for jobs (or `dx find executions` to include analyses as well)-- `dx find data` only operates on data objects (files, records, and the like).

**Comment by kislyuk** [comment]
@mjmonroe, thanks for your report! As @psung mentioned, `dx find jobs` or `dx find executions` is the appropriate way to search for jobs. Per DNAnexus nomenclature, jobs are considered *executions*, not *data objects* (which are searchable via `dx find data`).
