### ISSUE TITLE
dx-run-app-locally dies with `UnboundLocalError`

### ISSUE THREAD

**Issue by lgautier** [dnanexus/dx-toolkit#108]
Running
```
dx-run-app-locally my-app -imy-input=foo.txt
```

ends with:

```
Traceback (most recent call last):
  File "/usr/local/bin/dx-run-app-locally", line 161, in <module>
    local_exec_utils.run_entry_points(run_spec=dxapp_json['runSpec'])
  File "/usr/local/lib/python2.7/site-packages/dxpy/utils/local_exec_utils.py", line 461, in run_entry_points
    name=entry_point_to_run.get('name'))
  File "/usr/local/lib/python2.7/site-packages/dxpy/utils/local_exec_utils.py", line 367, in run_one_entry_point
    invocation_args = [arg.encode(sys.stdout.encoding) for arg in invocation_args]
UnboundLocalError: local variable 'invocation_args' referenced before assignment
```

(`dxpy` was pip-installed today: 
```
$ dx --version
dx v0.161.0
```

**Comment by lgautier** [comment]
It seems that testing for whenever `python` turns out to be a python 2.x, the variable `invocation_args` is not defined, leading to the `UnboundLocalError` reported above.

`invocation_args` is only defined if `run_spec['interpreter'] == 'python2.7'` 
(see https://github.com/dnanexus/dx-toolkit/blob/master/src/python/dxpy/utils/local_exec_utils.py#L350 )
while `USING_PYTHON2` is used as condition to encode the strings in `invocation_args`  
(see https://github.com/dnanexus/dx-toolkit/blob/master/src/python/dxpy/utils/local_exec_utils.py#L366 )

**Comment by kislyuk** [comment]
Thanks for reporting this, investigating.

**Comment by lgautier** [comment]
When running an Ubuntu 12.04 built exactly according to specs (https://wiki.dnanexus.com/Ubuntu-Repository), the process seem to go a little further yet still stop premature (and with a different error):
 
```
dx build dry run successful
Traceback (most recent call last):
  File "/usr/bin/dx-run-app-locally", line 12, in <module>
    __import__('pkg_resources').run_script('dxpy==0.161.0', 'dx-run-app-locally')
  File "/usr/bin/../share/dnanexus/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/bin/../share/dnanexus/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/share/dnanexus/lib/python2.7/site-packages/dxpy-0.161.0-py2.7.egg/EGG-INFO/scripts/dx-run-app-locally", line 83, in <module>
    job_inputs.update_from_args(args)
  File "/usr/share/dnanexus/lib/python2.7/site-packages/dxpy-0.161.0-py2.7.egg/dxpy/cli/exec_io.py", line 731, in update_from_args
    self._update_requires_resolution_inputs()
  File "/usr/share/dnanexus/lib/python2.7/site-packages/dxpy-0.161.0-py2.7.egg/dxpy/cli/exec_io.py", line 494, in _update_requires_resolution_inputs
    dxpy.bindings.verify_string_dxid(entity_result['id'], input_class)
TypeError: string indices must be integers
```

**Comment by kislyuk** [comment]
@lgautier, can you please paste `dxapp.json` for your `my-app`? There are certain assumptions that our code makes about the contents of that file. Some of them may need to be tightened up, but there are several `dxapp.json` entries that are mandatory for the app metadata to be valid - I just want to check what yours looks like and what we should do to correct the error or make it more intuitive. Also, did you write `dxapp.json` by hand, or copy it from elsewhere, or generate it with `dx-app-wizard`?

**Comment by lgautier** [comment]
The `dxapp.json` was programmatically generated (but not by `dx-app-wizard`, so you might consider it written by hand). It is essentially like follows (I edited `execDepends` out).
 
```json
{
 "name": "my-app", 
 "title": "This is \"my-app\"", 
 "outputSpec": [
  {
   "class": "file", 
   "help": "?", 
   "name": "index", 
   "label": "an index"
  }
 ], 
 "runSpec": {
  "interpreter": "python", 
  "systemRequirements": {
   "main": {
    "instanceType": "mem1_ssd1_x4"
   }
  }, 
  "file": "src/script.py", 
  "execDepends": [
  ]
 }, 
 "summary": "DNAnexus applet programmatically generated", 
 "access": {
  "network": [
   "*"
  ]
 }, 
 "version": "0.5.0-dev", 
 "inputSpec": [
  {
   "patterns": [
    "*.fa", 
    "*.fna", 
    "*.fasta", 
    "*.FASTA"
   ], 
   "class": "file", 
   "help": "?", 
   "name": "reference", 
   "label": "a reference"
  }
 ]
}
```

**Comment by kislyuk** [comment]
OK, great, thanks. Please note that we currently only support two values for `runSpec.interpreter`: "python2.7" and "bash", so this `dxapp.json` will not work. With that said, the error message should clearly state what is going on, so we will add a clause that will print the appropriate error in this case.

We are also looking at the second stack trace that you reported.

**Comment by kislyuk** [comment]
One more question regarding your second stack trace - was it generated using the same exact dxapp.json and the same command line, or was there anything different in how you ran it the second time?

**Comment by lgautier** [comment]
The second trace was generated using the very same app directory (which contains the `dxapp.json`). Not even a copy: the exact same (accessed from a Docker container in which everything is installed).

**Comment by kislyuk** [comment]
Hi @lgautier,

We have addressed the first issue you encountered with https://github.com/dnanexus/dx-toolkit/commit/c9fb2c995f18127c0da6b1364787b543e19a541e. We are still working on identifying the root cause for the second issue.

**Comment by lgautier** [comment]
`results`, defined at https://github.com/dnanexus/dx-toolkit/blob/master/src/python/dxpy/cli/exec_io.py#L455, turns out to be:

```
{u'foo.txt': {u'project': None, u'folder': u'/', u'name': u'foo.txt'}}
```

Later in the loop `input_value` is equal to `u'foo.txt'`, which leads to `entity_result` to be equal to `foo.txt`.
(since `entity_result = results['foo.txt']['name']`). `entity_result['id']` is then triggering the second error reported.

**Comment by psung** [comment]
Hello @lgautier, when you run

```
dx-run-app-locally my-app -imy-input=foo.txt
```

are you logged in to DNAnexus in that shell session and does `foo.txt` represent an accessible file on the platform? Just to clarify, although dx-run-app-locally will run the payload of your app locally, the inputs and outputs still refer to files already on DNAnexus (they will be downloaded or uploaded, respectively, during the local execution of the applet).

**Comment by lgautier** [comment]
It looks like the session expired or got reset: logging in again make the second error go away... only to hit an other error downstream.

I am looking whether the error makes senses to me (as in "indicates the source of the error").

In the meantime, it seems like `dx-run-app-locally` should check that a user is logged in and report it in an error message if not the case. Should I open a new issue about this ?

**Comment by lgautier** [comment]
Continued on issue #111

**Comment by psung** [comment]
Thanks for the follow-up. We'll make the error messages more sensible when the user is not logged in (no need to file a separate issue about that).

**Comment by psung** [comment]
This (the improvement to the error message when not logged in) is done in 41879fad.
