### ISSUE TITLE
`dx-run-app-locally` with an invalid path stops without an informative message.

### ISSUE THREAD

**Issue by lgautier** [dnanexus/dx-toolkit#109]
```bash
dx-run-app-locally /invalid/path/my-app -imy-input=foo.txt
```

stops without an informative error message.
The return code is `2` though.

**Comment by kislyuk** [comment]
Hi Laurent,

Thanks for pointing this out; we are working on making sure that code path produces an informative error message.

**Comment by kislyuk** [comment]
Hi Laurent,

Apologies for the delay in our response to this; I have identified the program and fixed it in the master branch. Per our standard procedure, this code will be released as part of a stable release next Wednesday, Oct 14, if all testing goes well.

Thanks again for identifying the issue.
