### ISSUE TITLE
OSX 10.11: Warning: readline module is not available, tab completion disabled

### ISSUE THREAD

**Issue by drmjc** [dnanexus/dx-toolkit#118]
Hi,
I think there's a problem with the gnureadline.so included in the dx-toolkit v0.169.1, downloaded from the OSX pre-made binary. When I run any dx command, I get this warning:

```
Warning: readline module is not available, tab completion disabled
```

I can trace this down to a bad gnureadline.so:

```
source environment
python
Python 2.7.10 (default, Aug 22 2015, 20:33:39) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import readline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marcow/apps/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/readline.py", line 1, in <module>
    from gnureadline import *
ImportError: dlopen(/Users/marcow/apps/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/gnureadline.so, 2): Library not loaded: /opt/local/lib/libncurses.5.dylib
  Referenced from: /Users/marcow/apps/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/gnureadline.so
  Reason: image not found
```

Inspecting the gnureadline.so

```
otool -L /Users/marcow/apps/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/gnureadline.so
/Users/marcow/apps/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/gnureadline.so:
/opt/local/lib/libncurses.5.dylib (compatibility version 5.0.0, current version 5.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
```

/opt is pretty empty on my system

```
ls /opt
X11/           cisco/         homebrew-cask/
```

Swapping out the offending gnureadline.so with this one `/Library/Python/2.7/site-packages/gnureadline.so` works well

cheers,
Mark

**Comment by pshapiro4claritas** [comment]
Thanks for this tip, I was puzzled by this as well. Replacing the dx copy of gnureadline.so with the one that I got from `$ pip install gnureadline` fixed the warning.

**Comment by geetduggal** [comment]
Hi -- we're doing some cleanup on the Github issues, and it looks like for recent versions of the toolkit on OS X do not have this issue anymore.  Thanks for reporting! I'll close it for now unless it is still an issue on your end.

**Comment by golharam** [comment]
I see this issue as well, however I can import readline without issue, and my gnureadline is already up to date:
$ pip install gnureadline
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: gnureadline in ./workspace/NGS/dnanexus-env/lib/python2.7/site-packages (6.3.8)

$ python
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 29 2018, 20:59:26) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import readline

**Comment by transcript** [comment]
I'm experiencing the same issue as golharam, above - on a fresh install of dx-toolkit, I get an error:

Warning: incompatible readline module detected (libedit), tab completion disabled

However, I am currently using gnureadline==6.3.8 (the required version), and have no trouble importing readline in Python 2.7.

Tab completion is, as the error message states, disabled.
