### ISSUE TITLE
dx describe should respect previous selection, if any ...

### ISSUE THREAD

**Issue by kedarmhaswade** [dnanexus/dx-toolkit#120]
```
bash-3.2$ dx select --level VIEW
Available projects (VIEW or higher):
0) A (VIEW)
1) B (VIEW)
2) C (CONTRIBUTE)

Pick a numbered choice or "m" for more options: 1
Setting current project to: B
bash-3.2$ dx describe .
DXCLIError: No matches found for .
```

I think this could be improved. `dx` already knows that my currently selected project is `2) B`. So, the character `.` should refer to that project. Is it possible to enhance `dx describe` behavior to this effect?

**Comment by psung** [comment]
"." refers to a folder (the root directory of project B); folders aren't first-class objects in the platform, and as such, they can't be described. If you wish to describe the project, you can use either of the following:

```
dx describe :  # describe the current project
dx describe "B:"  # describe any project, identified by its name
```

**Comment by kedarmhaswade** [comment]
Cool. Thanks. I must have missed that ':' refers to the current project.
