### ISSUE TITLE
Unable to access .jar file in resources

### ISSUE THREAD

**Issue by scienception** [dnanexus/dx-toolkit#1217]
Hi I saved my .jar file in resources/usr/bin however I get this error:

`Error: Unable to access jarfile SnpSift.jar 
`
I don't get this error with other types of binary files.

I want to run something like this:

` cat input_file | java -jar SnpSift.jar filter "((ANN[*].IMPACT = 'HIGH') | (ANN[*].IMPACT = 'MODERATE'))" > output_file
`
Is there something that I'm doing wrong?

**Comment by emiloslavsky** [comment]
Have you tried `java -jar /usr/bin/SnpSift.jar`?  If you still have this problem, please contact support@dnanexu.com for help.
