### ISSUE TITLE
Interest in playing with Bioconductor?

### ISSUE THREAD

**Issue by seandavi** [dnanexus/dx-toolkit#122]
I was looking over GXTables a bit and began to wonder if there is any interest in playing better with Bioconductor objects.  A GXTable has a lot of overlap (no pun intended) with GRanges objects, for which there exists a very rich for overlaps, transformations, import and export, etc.  Is there any interest in having an interface between dxR and Bioconductor objects?

**Comment by geetduggal** [comment]
Hi Sean, we are doing some cleanup on Github issues, and we have sunset GTables from the platform since. I'll go ahead and mark this issue closed unless there's any objection :)
