### ISSUE TITLE
folder size when using dx ls

### ISSUE THREAD

**Issue by wilmerwang** [dnanexus/dx-toolkit#1281]
hi, When using dx ls, can you add the function of displaying folder size?

**Comment by jethror1** [comment]
afaik there is no built in way to get a total folder size, this is what I have used previously to solve the issue using `dx find data`:
```
$ dx find data --path $(dx pwd) --verbose --json | jq -r '.[].describe.size' | paste -sd+ | bc
115342190356
```

this returns it in bytes, if you want to convert this to gigabytes you can use `bc`:
```
$ bc <<< "scale=2; $(dx find data --path $(dx pwd) --verbose --json | jq -r '.[].describe.size' |
 paste -sd+ | bc) / 1024 / 1024 / 1024"
107.42
```

**Comment by wilmerwang** [comment]
> afaik there is no built in way to get a total folder size, this is what I have used previously to solve the issue using `dx find data`:
> 
> ```
> $ dx find data --path $(dx pwd) --verbose --json | jq -r '.[].describe.size' | paste -sd+ | bc
> 115342190356
> ```
> 
> this returns it in bytes, if you want to convert this to gigabytes you can use `bc`:
> 
> ```
> $ bc <<< "scale=2; $(dx find data --path $(dx pwd) --verbose --json | jq -r '.[].describe.size' |
>  paste -sd+ | bc) / 1024 / 1024 / 1024"
> 107.42
> ```

It works well for me . Thank you!
