### ISSUE TITLE
dx-toolkit installation in Linux HPC

### ISSUE THREAD

**Issue by frahimov** [dnanexus/dx-toolkit#1319]
Is it possible to install dx-toolkit on a Linux shared cluster? I followed the instructions on https://documentation.dnanexus.com/downloads but it was nearly impossible to make it work.

**Comment by emiloslavsky** [comment]
The updated instructions at https://documentation.dnanexus.com/downloads rely on `pip3 install dxpy`.  Please re-open with more specific description of the installations problems you running into if the problem still persists.
