### ISSUE TITLE
feature request: range-request for `dx data download`

### ISSUE THREAD

**Issue by lindenb** [dnanexus/dx-toolkit#1346]
Hi all,

I'm not sure if it already exists or if it can/can't be implemented but it would be nice if ` dx data download` could have a 'range-request' option just like curl ( https://everything.curl.dev/http/ranges ).

For example, I want to extract a small chunck of data from a very large BAM file, I don't need to download the whole bam and its' index, I can ask for the data between byte 'x' and 'y'.

**Comment by emiloslavsky** [comment]
Thanks for the request.  For now, please use lower-level API e.g.
```
import dxpy
fd = dxpy.open_dxfile('file-xxxx')
fd.seek(skip_byte_count)
fd.read(read_byte_count)
```
