### ISSUE TITLE
Unfriendly with proxies

### ISSUE THREAD

**Issue by yhelothar** [dnanexus/dx-toolkit#168]
16:49:44 08/04/16 SGT>> --- Detected run 160115_D00240_0221_AH2NHLADXY
16:49:44 08/04/16 SGT>> DNANexus Folder: project-BkPyP980pzB920Q3JbYpbypQ:/data/runs/160115_D00240_0221_AH2NHLADXY
16:49:44 08/04/16 SGT>> Traceback (most recent call last):
16:49:44 08/04/16 SGT>>   File "/opt/gls/clarity/customextensions/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/dxpy/scripts/dx.py", line 4762, in main
16:49:44 08/04/16 SGT>>     args.func(args)
16:49:44 08/04/16 SGT>>   File "/opt/gls/clarity/customextensions/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/dxpy/scripts/dx.py", line 363, in login
16:49:44 08/04/16 SGT>>     dxpy.config.write("DX_USERNAME", dxpy.user_info(host, port)['username'])
16:49:44 08/04/16 SGT>>   File "/opt/gls/clarity/customextensions/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/dxpy/bindings/auth.py", line 32, in user_info
16:49:44 08/04/16 SGT>>     return DXHTTPRequest(authserver + "/system/getUserInfo", {}, prepend_srv=False)
16:49:44 08/04/16 SGT>>   File "/opt/gls/clarity/customextensions/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/dxpy/**init**.py", line 592, in DXHTTPRequest
16:49:44 08/04/16 SGT>>     _get_pool_manager(**pool_args).clear()
16:49:44 08/04/16 SGT>>   File "/opt/gls/clarity/customextensions/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/dxpy/__init__.py", line 244, in _get_pool_manager
16:49:44 08/04/16 SGT>>     _pool_manager = urllib3.ProxyManager(**default_pool_args)
16:49:44 08/04/16 SGT>>   File "/opt/gls/clarity/customextensions/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/requests/packages/urllib3/poolmanager.py", line 231, in __init__
16:49:44 08/04/16 SGT>>     'Not supported proxy scheme %s' % proxy.scheme
16:49:44 08/04/16 SGT>> AssertionError: Not supported proxy scheme None
16:49:44 08/04/16 SGT>> ERROR: Invalid API token. Cannot login
16:49:44 08/04/16 SGT>> An error occurred in uploading of BCL files, please contact the LIMS administration team. Thank you.
16:49:44 08/04/16 SGT>> Unexpected error:!! Traceback (most recent call last):
!!   File "bclUpload.py", line 396, in main
    uploadBCL( runDir, runFolder)
!!   File "bclUpload.py", line 270, in uploadBCL
    eMsg = "Dear User,\n\n An error has occurred in process" + hostname + "/clarity/work-details/" + (args["processID"].split("-"))[1] + " while trying to upload the sequencing folder onto DNAnexus, retries were in vain. Please contact the LIMS administrator team.\n\n Error: " + errMsg + "\n\n Thank you."
!! NameError: global name 'hostname' is not defined

**Comment by yhelothar** [comment]
I have an environment variable in my script that sets an HTTPS proxy. It worked great in the older dx-toolkit versions but it's posing an issue with the new version.

**Comment by serverhorror** [comment]
Same here, we cannot use DNAnexus any more.

**dx-toolkit version**

```
$ dx --version
dx v0.225.0
```

**dx-toolkit login attempt**

```
$ dx login
Acquiring credentials from https://auth.dnanexus.com
Username [martin]:
Password:
WARNING:dxpy:[Tue Oct 10 11:54:44 2017] POST https://auth.dnanexus.com/system/newAuthToken: ProtocolError: ('Connection aborted.', error(110, 'Connection timed out')). Waiting 1 seconds before retry 1 of 6...
WARNING:dxpy:[Tue Oct 10 11:56:52 2017] POST https://auth.dnanexus.com/system/newAuthToken: ProtocolError: ('Connection aborted.', error(110, 'Connection timed out')). Waiting 2 seconds before retry 2 of 6...
WARNING:dxpy:[Tue Oct 10 11:59:02 2017] POST https://auth.dnanexus.com/system/newAuthToken: ProtocolError: ('Connection aborted.', error(110, 'Connection timed out')). Waiting 4 seconds before retry 3 of 6...
WARNING:dxpy:[Tue Oct 10 12:01:13 2017] POST https://auth.dnanexus.com/system/newAuthToken: ProtocolError: ('Connection aborted.', error(110, 'Connection timed out')). Waiting 4 seconds before retry 4 of 6...
WARNING:dxpy:[Tue Oct 10 12:03:24 2017] POST https://auth.dnanexus.com/system/newAuthToken: ProtocolError: ('Connection aborted.', error(110, 'Connection timed out')). Waiting 9 seconds before retry 5 of 6...
WARNING:dxpy:[Tue Oct 10 12:05:41 2017] POST https://auth.dnanexus.com/system/newAuthToken: ProtocolError: ('Connection aborted.', error(110, 'Connection timed out')). Waiting 32 seconds before retry 6 of 6...
ERROR:dxpy:[Tue Oct 10 12:08:20 2017] POST https://auth.dnanexus.com/system/newAuthToken: ProtocolError: ('Connection aborted.', error(110, 'Connection timed out')).
ProtocolError: ('Connection aborted.', error(110, 'Connection timed out'))
dx: Login error: ('Connection aborted.', error(110, 'Connection timed out'))
```

**requests to test wether connection works**

```
$ python -c "import requests; requests.get('https://auth.dnanexus.com')"
$ echo $?
0
```

**purposely failing with requests**

```
$ python -c "import requests; requests.get('https://auth.invalid')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/apps/prod/easybuild/sl7.x86_64/software/dxpy/0.225.0-foss-2016b/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/apps/prod/easybuild/sl7.x86_64/software/dxpy/0.225.0-foss-2016b/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/apps/prod/easybuild/sl7.x86_64/software/dxpy/0.225.0-foss-2016b/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/apps/prod/easybuild/sl7.x86_64/software/dxpy/0.225.0-foss-2016b/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/apps/prod/easybuild/sl7.x86_64/software/dxpy/0.225.0-foss-2016b/lib/python2.7/site-packages/requests/adapters.py", line 424, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='auth.invalid', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 503 Service Unavailable',)))
$ echo $?
1
```

**environment has proxy setting set (CNTLM)**

```
$ echo $http_proxy
http://127.0.0.1:5865
```

**curl also works**

```
$ curl -o /dev/null -v  https://auth.dnanexus.com
* About to connect() to proxy 127.0.0.1 port 5865 (#0)
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 5865 (#0)
* Establish HTTP proxy tunnel to auth.dnanexus.com:443
> CONNECT auth.dnanexus.com:443 HTTP/1.1
> Host: auth.dnanexus.com:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
< Date: Tue, 10 Oct 2017 10:17:52 GMT
< Via: 1.1 ingpx04.eu.boehringer.com:80 (Cisco-WSA/9.1.2-039)
< Connection: close
<
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=auth.dnanexus.com,OU=Domain Control Validated
*       start date: Apr 26 17:00:39 2016 GMT
*       expire date: Apr 26 17:00:39 2018 GMT
*       common name: auth.dnanexus.com
*       issuer: CN=Go Daddy Secure Certificate Authority - G2,OU=http://certs.godaddy.com/repository/,O="GoDaddy.com, Inc.",L=Scottsdale,ST=Arizona,C=US
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: auth.dnanexus.com
> Accept: */*
>
< HTTP/1.1 302 FOUND
< Server: nginx
< Date: Tue, 10 Oct 2017 10:17:53 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 265
< Connection: keep-alive
< Location: https://platform.dnanexus.com
< Access-Control-Expose-Headers: Retry-After
< Cache-Control: no-cache, no-store
< Pragma: no-cache
< Expires: 0
<
{ [data not shown]
100   265  100   265    0     0    204      0  0:00:01  0:00:01 --:--:--   204
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by geetduggal** [comment]
Hi and thanks for this detailed information.  Could you try setting this environment variable `export HTTPS_PROXY=http://127.0.0.1:5865`?   It may be at one point the `http_proxy` worked but it looks like we switched to a new way of managing the connections that explicitly uses the HTTPS_PROXY env var (regardless of whether it is HTTP/HTTPS).   If that doesn't work we can iterate from there.   Thanks in advance!

**Comment by pelacables** [comment]
Hi, I work with @serverhorror .
We do set both varibles: http_proxy and https_proxy (I belive @serverhorror forgot to "echo" both variables).
(Or are you refering to the env variable in capital letters HTTPS_PROXY insetad of https_proxy?)

Best,

**Comment by geetduggal** [comment]
Gotcha. Could you try the capital version?  Thanks in advance!

**Comment by geetduggal** [comment]
(Also, we created a ticket to allow for multiple options)

**Comment by serverhorror** [comment]
I'll report back tomorrow on upper/lower case.

May I suggest you explicitely make sure to accept both? I find it to be a constant source of confusion with users. It is not helpful either that Windows (by default) seems to user upper case and Linux (again, by default or rather majority vote) seems to accept lower case.

One piece of information (consider this a _note to self_ so I won't forget to check). The current client uses a company proxy that opens up SSL and inspects content. Could it be that this is the trouble?

The flow is like this:

1. dx login
1. Proxy receives request and presents a valid and signed cert (signed by CA distributed and trusted by the OS)
1. ..(content inspection)...
1. Proxy creates a new request to target (`auth.dnanexus.com` in our case) and forwards payload

I guess we'd see something different than a connection timeout then. Just mentioning this in case you do some kind of certificate pinning. And the `requests` code snippet would show a different CA.

Yes this presents a MITM-attack. But in this case it is valid since it is mandated by internal regulations to be able to access all traffic, incoming as well as outgoing. I've seen this quite a bunch of times at larger clients and it almost always presents a huge challenge to get IT security to sign off on this so one is able to use service that do certificate pinning or similiar. Unfortunately the enterprise products too often **do not** modify all the required headers, let alone if the certificate pins are in the client and the public key is checked purely on client side.

**Comment by geetduggal** [comment]
Agreed. We'll make sure to allow the various permutations of env variable names.  Thanks for the additional details on the SSL proxy flow -- if the capital env var issue doesn't work this may help us to debug further.

**Comment by pelacables** [comment]
Morning,

```bash
$ env |grep -i _proxy
http_proxy=http://127.0.0.1:5865
HTTPS_PROXY=http://127.0.0.1:5865
https_proxy=http://127.0.0.1:5865
HTTP_PROXY=http://127.0.0.1:5865
$ dx login
Acquiring credentials from https://auth.dnanexus.com
Username [bria]:
Password:
New messages from DNAnexus
Date:    Tue Sep 26 17:05:15 2017
Subject: Have you upgraded to TLS 1.2 yet?
Message: We are switching to TLS 1.2 on October 15th, 2017 and turning off support for TLS 1.0/1.1 after that date. Please refer to our blog post at https://blog.dnanexus.com/2017-09-23-upgrading-tls/ regarding upgrading to TLS 1.2.
Date:    Wed Oct 11 08:48:50 2017
Subject: TLS version
Message: Your connection was established successfully using TLS v1.2.
```

So using HTTPS_PROXY fixes the issue.

Best,

**Comment by mdshw5** [comment]
Same issue here. Would definitely like to see a new release that allows case insensitive variables at least.

**Comment by geetduggal** [comment]
Interesting, I swear I reviewed a commit allowing case insensitive and other common env vars lol, but it looks like it is not there.  We'll try to get this out in an upcoming release.

**Comment by geetduggal** [comment]
Found it: was addressed by this: https://github.com/dnanexus/dx-toolkit/pull/250.  Looks like someone else on the team just merged it :)
