### ISSUE TITLE
When installed with pip, gnureadline won't override system readline module

### ISSUE THREAD

**Issue by tdsmith** [dnanexus/dx-toolkit#169]
When gnureadline is installed with pip, it will not override the system readline module. This means when dxpy is installed with pip, the injected gnureadline dependency doesn't do anything. The most durable solution is to try to import `gnureadline` instead of importing `readline` at the point of use, falling back to `readline` if the import fails.

**Comment by geetduggal** [comment]
Hi, we are cleaning up issues in Github and we will look into this.  Are you still experiencing this issue?  Thanks for reporting!

**Comment by ilovezfs** [comment]
@geetduggal well yes it's still an issue because the import statements were not changed to `import gnureadline`.
