### ISSUE TITLE
includeSubjobs doesn't work in Java API

### ISSUE THREAD

**Issue by pkokoshnikov** [dnanexus/dx-toolkit#176]
Hi,

I need to find jobs in project without subjobs via Java API. I tried to do it via console and it works correctly dx find jobs --project project-Bz3GG980pFp8gB8K9bQggQ8j --no-subjobs. 
I found method: public DXSearch.FindExecutionsRequestBuilder<T> includeSubjobs(boolean includeSubjobs). 
I tried
DXSearch.findExecutionsWithEnvironment(projectEnvironment).inProject(project).withClassJob().includeSubjobs(false).execute(). But it returns jobs with subjbos. 

Version of dnanexus api is 0.190.1

Regards,
Pavel Kokoshnikov

**Comment by psung** [comment]
Hi Pavel,

That's very odd. It is the intention that `includeSubjobs(false)` in the Java bindings should be equivalent to specifying `--no-subjobs` in `dx`. Can you give an example of jobs that were returned that you didn't expect to see, or vice versa? (If there is any sensitive info you'd like to share, you can also email me directly, psung@dnanexus.com.)

Thanks,
Phil
