### ISSUE TITLE
SDK Build failure on OSX 10.11.6

### ISSUE THREAD

**Issue by bertgoldphd** [dnanexus/dx-toolkit#180]
bgold-macpro:Documents bgold$ pwd
/Users/bgold/Documents
bgold-macpro:Documents bgold$ ls -l
total 0
drwxr-xr-x   7 bgold  1574293677   238 Jul  6 18:29 Atlas2_v1.4.3
drwx------   4 bgold  1574293677   136 Jul  1 17:59 GenomeAnalysisTK-3.6
drwxr-xr-x   3 bgold  1574293677   102 Jul  2 18:04 NateraJuly
drwxr-xr-x  19 bgold  1574293677   646 Sep 22 22:27 dx-toolkit
drwxr-xr-x  13 bgold  1574293677   442 Jun 24 07:32 jvarkit-master
drwxr-xr-x   8 bgold  1574293677   272 Aug  8 16:00 mosaik
drwxr-xr-x  33 bgold  1574293677  1122 Jul  1 17:59 novocraft
bgold-macpro:Documents bgold$ cd dx-toolkit
bgold-macpro:dx-toolkit bgold$ ls -l
total 64
-rw-r--r--   1 bgold  1574293677  11358 Jan 28  2013 COPYING
-rw-r--r--   1 bgold  1574293677   1398 Jul 28 11:40 Readme-osx-10.9.md
-rw-r--r--   1 bgold  1574293677   3264 Sep 22 14:53 Readme.md
drwxr-xr-x  48 bgold  1574293677   1632 Sep 22 22:25 bin
drwxr-xr-x  17 bgold  1574293677    578 Sep 22 22:25 build
drwxr-xr-x   4 bgold  1574293677    136 Jun 10  2014 doc
-rwxrwxrwx   1 bgold  1574293677   2860 Mar 24  2016 environment
-rw-r--r--   1 bgold  1574293677   1304 Jul 28 11:40 environment.bat
-rw-r--r--   1 bgold  1574293677   1640 Mar 24  2016 environment.csh
drwxr-xr-x   4 bgold  1574293677    136 Sep 22 22:20 lib
drwxr-xr-x   3 bgold  1574293677    102 Sep 22 22:20 share
drwxr-xr-x  12 bgold  1574293677    408 Sep 22 22:25 src
bgold-macpro:dx-toolkit bgold$ ./environment
bgold-macpro:dx-toolkit bgold$ dx login
Traceback (most recent call last):
  File "/Users/bgold/Documents/dx-toolkit/bin/dx", line 7, in <module>
    from dxpy.scripts.dx import main
ImportError: No module named dxpy.scripts.dx
bgold-macpro:dx-toolkit bgold$ pip install dxpy
Collecting dxpy
Requirement already satisfied (use --upgrade to upgrade): fusepy==2.0.2 in /usr/local/lib/python2.7/site-packages (from dxpy)
Collecting xattr==0.6.4 (from dxpy)
  Using cached xattr-0.6.4.tar.gz
Collecting futures==3.0.4 (from dxpy)
  Using cached futures-3.0.4-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): python-magic==0.4.6 in /usr/local/lib/python2.7/site-packages (from dxpy)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil==2.3 in /usr/local/lib/python2.7/site-packages (from dxpy)
Requirement already satisfied (use --upgrade to upgrade): ws4py==0.3.2 in /usr/local/lib/python2.7/site-packages (from dxpy)
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4==4.4.1 in /usr/local/lib/python2.7/site-packages (from dxpy)
Collecting psutil==3.3.0 (from dxpy)
  Using cached psutil-3.3.0.tar.gz
Collecting requests==2.7.0 (from dxpy)
  Using cached requests-2.7.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/site-packages (from python-dateutil==2.3->dxpy)
Building wheels for collected packages: xattr, psutil
  Running setup.py bdist_wheel for xattr ... error
  Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;**file**='/private/var/folders/9w/d_1m0pmn36l4xkntq3gqyn4s7jn86h/T/pip-build-HuZxGp/xattr/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" bdist_wheel -d /var/folders/9w/d_1m0pmn36l4xkntq3gqyn4s7jn86h/T/tmpy8cVwCpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.11-x86_64-2.7
  creating build/lib.macosx-10.11-x86_64-2.7/xattr
  copying xattr/**init**.py -> build/lib.macosx-10.11-x86_64-2.7/xattr
  copying xattr/constants.py -> build/lib.macosx-10.11-x86_64-2.7/xattr
  copying xattr/tool.py -> build/lib.macosx-10.11-x86_64-2.7/xattr
  running build_ext
  building 'xattr._xattr' extension
  creating build/temp.macosx-10.11-x86_64-2.7
  creating build/temp.macosx-10.11-x86_64-2.7/xattr
  gcc-4.7 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c xattr/_xattr.c -o build/temp.macosx-10.11-x86_64-2.7/xattr/_xattr.o
  unable to execute 'gcc-4.7': No such file or directory
  error: command 'gcc-4.7' failed with exit status 1

---

  Failed building wheel for xattr
  Running setup.py clean for xattr
  Running setup.py bdist_wheel for psutil ... error
  Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;**file**='/private/var/folders/9w/d_1m0pmn36l4xkntq3gqyn4s7jn86h/T/pip-build-HuZxGp/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" bdist_wheel -d /var/folders/9w/d_1m0pmn36l4xkntq3gqyn4s7jn86h/T/tmpnPxqrYpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.11-x86_64-2.7
  creating build/lib.macosx-10.11-x86_64-2.7/psutil
  copying psutil/**init**.py -> build/lib.macosx-10.11-x86_64-2.7/psutil
  copying psutil/_common.py -> build/lib.macosx-10.11-x86_64-2.7/psutil
  copying psutil/_compat.py -> build/lib.macosx-10.11-x86_64-2.7/psutil
  copying psutil/_psbsd.py -> build/lib.macosx-10.11-x86_64-2.7/psutil
  copying psutil/_pslinux.py -> build/lib.macosx-10.11-x86_64-2.7/psutil
  copying psutil/_psosx.py -> build/lib.macosx-10.11-x86_64-2.7/psutil
  copying psutil/_psposix.py -> build/lib.macosx-10.11-x86_64-2.7/psutil
  copying psutil/_pssunos.py -> build/lib.macosx-10.11-x86_64-2.7/psutil
  copying psutil/_pswindows.py -> build/lib.macosx-10.11-x86_64-2.7/psutil
  running build_ext
  building 'psutil._psutil_osx' extension
  creating build/temp.macosx-10.11-x86_64-2.7
  creating build/temp.macosx-10.11-x86_64-2.7/psutil
  creating build/temp.macosx-10.11-x86_64-2.7/psutil/arch
  creating build/temp.macosx-10.11-x86_64-2.7/psutil/arch/osx
  gcc-4.7 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DPSUTIL_VERSION=330 -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c psutil/_psutil_osx.c -o build/temp.macosx-10.11-x86_64-2.7/psutil/_psutil_osx.o
  unable to execute 'gcc-4.7': No such file or directory
  error: command 'gcc-4.7' failed with exit status 1

---

  Failed building wheel for psutil
  Running setup.py clean for psutil
Failed to build xattr psutil
Installing collected packages: xattr, futures, psutil, requests, dxpy
  Running setup.py install for xattr ... error
    Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;**file**='/private/var/folders/9w/d_1m0pmn36l4xkntq3gqyn4s7jn86h/T/pip-build-HuZxGp/xattr/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/9w/d_1m0pmn36l4xkntq3gqyn4s7jn86h/T/pip-EJmUF_-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-x86_64-2.7
    creating build/lib.macosx-10.11-x86_64-2.7/xattr
    copying xattr/**init**.py -> build/lib.macosx-10.11-x86_64-2.7/xattr
    copying xattr/constants.py -> build/lib.macosx-10.11-x86_64-2.7/xattr
    copying xattr/tool.py -> build/lib.macosx-10.11-x86_64-2.7/xattr
    running build_ext
    building 'xattr._xattr' extension
    creating build/temp.macosx-10.11-x86_64-2.7
    creating build/temp.macosx-10.11-x86_64-2.7/xattr
    gcc-4.7 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c xattr/_xattr.c -o build/temp.macosx-10.11-x86_64-2.7/xattr/_xattr.o
    unable to execute 'gcc-4.7': No such file or directory
    error: command 'gcc-4.7' failed with exit status 1

```
----------------------------------------
```

Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;**file**='/private/var/folders/9w/d_1m0pmn36l4xkntq3gqyn4s7jn86h/T/pip-build-HuZxGp/xattr/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/9w/d_1m0pmn36l4xkntq3gqyn4s7jn86h/T/pip-EJmUF_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/9w/d_1m0pmn36l4xkntq3gqyn4s7jn86h/T/pip-build-HuZxGp/xattr/
bgold-macpro:dx-toolkit bgold$

**Comment by psung** [comment]
Hi @bertgoldphd, have you installed gcc (and other dependencies) using the instructions here? https://github.com/dnanexus/dx-toolkit#os-x

**Comment by bertgoldphd** [comment]
yes, of course..

it should be clear from my output that what is failing to install
is pip install dxpy

Bert

Bert Gold, Ph.D., FACMGG
Senior Clinical Molecular Geneticist
Natera, Inc.
201 Industrial Rd
San Carlos, California
EMAIL: bgold@natera.com
OFFICE: (650) 249-9090 extension 1537
CELL: (302) 507-1827

**Comment by psung** [comment]
@billagee, any ideas on what is happening here?

**Comment by bertgoldphd** [comment]
Note that there was a new install of Xcode tools a week or so ago and that
there have been some bad interactions with Homebrew reported recently...
 viz-- (unrelated program,):

Wang, Liguo, Ph.D.
Sep 12
to me
Hi Bert,

I 90% sure the problem was caused by home-brew. Some one reported  this
problem before.

Liguo

From: Bert Gold <bgold@natera.com>
Date: Monday, September 12, 2016 at 9:57 AM
To: "Wang, Liguo, Ph.D." <wang.liguo@mayo.edu>
Subject: Re: Crossmap issue...

Dear Liguo,

bx-python is installed and I *did* use pip on Yosemite

I am going to try on my personal 10.8 machine.

I don't know why my configuration is messed up.

I tried de-installing and reinstalling several times

and I can send you my .bash_profile if that's where the

problem is....

I use homebrew extensively, so maybe its an incompatibility in

the way I installed python.

-Bert

Bert Gold, Ph.D., FACMGG
Senior Clinical Molecular Geneticist
Natera, Inc.
201 Industrial Rd
San Carlos, California
EMAIL: bgold@natera.com
OFFICE: (650) 249-9090 extension 1537
CELL: (302) 507-1827

Bert Gold, Ph.D., FACMGG
Senior Clinical Molecular Geneticist
Natera, Inc.
201 Industrial Rd
San Carlos, California
EMAIL: bgold@natera.com
OFFICE: (650) 249-9090 extension 1537
CELL: (302) 507-1827

**Comment by billagee** [comment]
Hi @bertgoldphd,

To see if we can set up a repro environment similar to yours, here are a few questions about the Python installation in your environment:

* If you download the latest prebuilt dx-toolkit tarball for OS X, then source its environment file, do you still see an error when running `dx login`?

    To do that, I use these steps:

    ```
    wget https://wiki.dnanexus.com/images/files/dx-toolkit-v0.200.3-osx.tar.gz
    tar zxf dx-toolkit-v0.200.3-osx.tar.gz
    
    source dx-toolkit/environment
    dx login
    ```

* Was homebrew used to install the release of python you're using?

Thank you!

**Comment by bertgoldphd** [comment]
I solved it.

It was an issue with the install of Xcode tools from a few days ago.

You must apparently start a project in order to activate the tools

AND it is important to do a rarely understood series of steps:

(ridiculous, I know):

https://ohthehugemanatee.org/blog/2015/10/01/how-i-got-el-capitain-working-with-my-developer-tools/

Bert

Bert Gold, Ph.D., FACMGG
Senior Clinical Molecular Geneticist
Natera, Inc.
201 Industrial Rd
San Carlos, California
EMAIL: bgold@natera.com
OFFICE: (650) 249-9090 extension 1537
CELL: (302) 507-1827
