### ISSUE TITLE
dx-app-wizard crashes

### ISSUE THREAD

**Issue by chruit** [dnanexus/dx-toolkit#193]
Using version 0.203.0 of dxpy on Ubuntu 14.0.4, dx-app-wizard crashes after entering a summary of a new app.  Traceback is below

The summary of your app is a short phrase or one-line description of what your app does.  It
can be any UTF-8 human-readable string.
Summary []: Short summary of app
Traceback (most recent call last):
  File "/usr/local/bin/dx-app-wizard", line 81, in <module>
    title, summary, description = get_metadata(API_VERSION)
ValueError: need more than 2 values to unpack

**Comment by nicolasbockg** [comment]
Hi @chruit, 
In version 0.203.0, the line you mention is not present anymore, so it seems like an older version of the dx-app-wizard is being called. Are you using a dx toolkit downloaded from the dnanexus downloads page, or are you building from source? 
If you are building from source, try to do this in your dx-toolkit/src directory:
`make clean
make python`
This should rebuild the dx-app-wizard.
Let us know if you are still having problems.

**Comment by chruit** [comment]
Hi @nicolasbockg 

Thanks for your response.  I initially installed the packages via the instructions on this site: 

https://wiki.dnanexus.com/Ubuntu-Repository

Since that didn't work, I downloaded the latest source code (0.205.2).  I was unable to run "make python" without errors.  In the end I copied over the files that existed in the bin directory to my system and that seems to have fixed the issues.

**Comment by nicolasbockg** [comment]
I am glad you were able to make it work.
Using the Ubuntu repository, you should most likely not need to run `make`. 
Maybe you were missing running the last command in the instructions to set the environment in the current terminal:
`source /etc/profile.d/dnanexus.environment.sh`
This adds the executables to your PATH.
Again, let us know if you still have issues.
