### ISSUE TITLE
Download all inputs regression due to PTFM-18767

### ISSUE THREAD

**Issue by Damien-Black** [dnanexus/dx-toolkit#203]
Changes from [PTFM-18767](https://github.com/dnanexus/dx-toolkit/blob/90902a101935b30f53659a033e5d5c6ddd976505/src/python/dxpy/bindings/download_all_inputs.py#L189-L194) results in usage of `dxpy.download_all_inputs(parallel=True)` to hang and slowly eat available memory.

`max_threads` is still an optional parameter that [is not set to a default value](https://github.com/dnanexus/dx-toolkit/commit/90902a101935b30f53659a033e5d5c6ddd976505#diff-d9c1c9ff7742a1569532d53081ead50cL182) before being used in [`min()`](https://github.com/dnanexus/dx-toolkit/commit/90902a101935b30f53659a033e5d5c6ddd976505#diff-d9c1c9ff7742a1569532d53081ead50cR112) to find the number of parallel workers. As a result Number of workers is always [set to None](https://github.com/dnanexus/dx-toolkit/blob/90902a101935b30f53659a033e5d5c6ddd976505/src/python/dxpy/bindings/download_all_inputs.py#L63).

Probably add the default value for `max_threads` back. Perhaps handle `max_workers=0` for ThreadPoolExecutor constructor?

**Comment by kpjensen** [comment]
Fixed in 2a08415
