### ISSUE TITLE
ordinal not in range when using App Wizard

### ISSUE THREAD

**Issue by drjrm3** [dnanexus/dx-toolkit#207]
I am trying to create a simple bash app and getting the following error when 'common instance types' should be coming up:

> Traceback (most recent call last):
>   File "/hpcf/apps/dx-toolkit/install/0.199.0/bin/dx-app-wizard", line 11, in <module>
>     sys.exit(main())
>   File "/hpcf/apps/dx-toolkit/install/0.199.0/src/python/dxpy/scripts/dx_app_wizard.py", line 370, in main
>     column_names=InstanceTypesCompleter.instance_types.values()[0]._fields))
>   File "/hpcf/apps/dx-toolkit/install/0.199.0/src/python/dxpy/compat.py", line 105, in write
>     TextIOWrapper.write(self, text)
> UnicodeEncodeError: 'ascii' codec can't encode character u'\u250c' in position 5: ordinal not in range(128)

The entire Q/A is as follows:

> DNAnexus App Wizard, API v1.0.0
> 
> Basic Metadata
> 
> Please enter basic metadata fields that will be used to describe your app.  Optional fields are
> denoted by options with square brackets.  At the end of this wizard, the files necessary for
> building your app will be generated from the answers you provide.
> 
> The name of your app must be unique on the DNAnexus platform.  After creating your app for
> the first time, you will be able to publish new versions using the same app name.  App names are
> restricted to alphanumeric characters (a-z, A-Z, 0-9), and the characters ".", "_", and "-".
> App Name [jrm3_HowdyWorld]: 
> 
> The title, if provided, is what is shown as the name of your app on the website.  It can be
> any valid UTF-8 string.
> Title []: 
> 
> The summary of your app is a short phrase or one-line description of what your app does.  It
> can be any UTF-8 human-readable string.
> Summary []: 
> 
> You can publish multiple versions of your app, and the version of your app is a string with
> which to tag a particular version.  We encourage the use of Semantic Versioning for labeling your
> apps (see http://semver.org/ for more details).
> Version [0.0.1]: 
> 
> Input Specification
> 
> You will now be prompted for each input parameter to your app.  Each parameter should have a unique
> name that uses only the underscore "_" and alphanumeric characters, and does not start with a
> number.
> 
> 1st input name (<ENTER> to finish): input_str
> Label (optional human-readable name) []: 
> Your input parameter must be of one of the following classes:
> applet         array:file     array:record   file           int
> array:applet   array:float    array:string   float          record
> array:boolean  array:int      boolean        hash           string
> 
> Choose a class (<TAB> twice for choices): string
> This is an optional parameter [y/n]: y
> A default value should be provided [y/n]: None
> 
> 2nd input name (<ENTER> to finish): 
> 
> Output Specification
> 
> You will now be prompted for each output parameter of your app.  Each parameter should have a unique
> name that uses only the underscore "_" and alphanumeric characters, and does not start with a
> number.
> 
> 1st output name (<ENTER> to finish): output_str
> Label (optional human-readable name) []: 
> Choose a class (<TAB> twice for choices): string
> 
> 2nd output name (<ENTER> to finish): 
> 
> Timeout Policy
> 
> Set a timeout policy for your app. Any single entry point of the app that runs longer than
> the specified timeout will fail with a TimeoutExceeded error. Enter an int greater than 0 with a
> single-letter suffix (m=minutes, h=hours, d=days) (e.g. "48h").
> Timeout policy [48h]: 
> 
> Template Options
> 
> You can write your app in any programming language, but we provide templates for the
> following supported languages: Python, bash
> Programming language: bash
> 
> Access Permissions
> If you request these extra permissions for your app, users will see this fact when launching your
> app, and certain other restrictions will apply. For more information, see
> https://wiki.dnanexus.com/App-Permissions.
> 
> Access to the Internet (other than accessing the DNAnexus API).
> Will this app need access to the Internet? [y/N]: N
> 
> Direct access to the parent project. This is not needed if your app specifies outputs,
> which will be copied into the project after it's done running.
> Will this app need access to the parent project? [y/N]: N
> 
> System Requirements
> 
> Common instance types:
> Traceback (most recent call last):
>   File "/hpcf/apps/dx-toolkit/install/0.199.0/bin/dx-app-wizard", line 11, in <module>
>     sys.exit(main())
>   File "/hpcf/apps/dx-toolkit/install/0.199.0/src/python/dxpy/scripts/dx_app_wizard.py", line 370, in main
>     column_names=InstanceTypesCompleter.instance_types.values()[0]._fields))
>   File "/hpcf/apps/dx-toolkit/install/0.199.0/src/python/dxpy/compat.py", line 105, in write
>     TextIOWrapper.write(self, text)
> UnicodeEncodeError: 'ascii' codec can't encode character u'\u250c' in position 5: ordinal not in range(128)

**Comment by mckinsel** [comment]
Hi @drjrm3, could you tell me what you get for these two python statements on the same computer where you're running dx_app_wizard.py?

```python
import locale, sys

sys.stdout.encoding
locale.getdefaultlocale()
```

**Comment by drjrm3** [comment]
Attempting to reproduce this to validate that I am on the same host and I am no longer able to reproduce this issue.
