### ISSUE TITLE
dx-app-wizard

### ISSUE THREAD

**Issue by a-frantz** [dnanexus/dx-toolkit#214]
Unicode error every time I try to run the app wizard. I've attempted running out of a windows environment and a linux environment. Same error either way. Happens in both dx-toolkit/0.199.0 and 0.212.0.

![dx-app-wizard_bug](https://cloud.githubusercontent.com/assets/28660237/26016739/f27c17ce-372b-11e7-915c-59a4fbf37667.jpg)

**Comment by geetduggal** [comment]
Hi,

If the environment variable `PYTHONIOENCODING=ascii` this error may occur.   Did you run `source dx-toolkit/environment` by any chance, as it sets it in there?

Thanks for reporting

**Comment by a-frantz** [comment]
Yes that resolved the error.


Thank you

________________________________
