### ISSUE TITLE
dx download

### ISSUE THREAD

**Issue by caot** [dnanexus/dx-toolkit#244]
It looks that the backend of "dx download" is using curl. is there a way to limit the download limit-rate ?

**Comment by kpjensen** [comment]
`dx download` uses dxpy and urllib3.
You could create a pre-authenticated download url with `dx make_download_url file-id` and then pass that to curl if you want to limit the rate that way.

**Comment by caot** [comment]
What is a good and easy way to limit the rate?

**Comment by kpjensen** [comment]
See the wiki link for help info regarding `dx make_download_url file-id` https://wiki.dnanexus.com/Command-Line-Client/Index-of-dx-Commands#make_download_url
This will return a pre-authenticated URL.
For example to create a URL and then download at a limited rate of 52 KB/S.
```
URL=$(dx make_download_url file-id)
curl -O --limit-rate 52k $URL
```
