### ISSUE TITLE
dx-docker does not pull images from docker hub

### ISSUE THREAD

**Issue by psafont** [dnanexus/dx-toolkit#270]
Hi!

Maybe I've misunderstood what `dx-docker` does, but I thought it could be used as a drop-in replacement for docker when using `cwltool`, this includes being able to pull images.

When I try to pull images from docker hub this happens:
```
$ dx-docker pull registry.hub.docker.com/psafont/ebitools:20170602
Error. Retrying in 1 s.
Error. Retrying in 2 s.
Error. Retrying in 4 s.
Traceback (most recent call last):
  File "/home/psafont/.config/virtualenvs/cwl/bin/dx-docker", line 471, in <module>
    args.func(args)
  File "/home/psafont/.config/virtualenvs/cwl/bin/dx-docker", line 95, in wrapper
    raise retry_exception
Exception: Failed to obtain image registry.hub.docker.com/psafont/ebitools:20170602.  Does this image exist in the specified repository?

[Errno 2] No such file or directory
```

Removing the `dx-` from the command to use the docker daemon works fine:
```
$ docker pull registry.hub.docker.com/psafont/ebitools:20170602
20170602: Pulling from psafont/ebitools
10a267c67f42: Pull complete
fb5937da9414: Pull complete
9021b2326a1e: Pull complete
dbed9b09434e: Pull complete
9ed9301d5505: Pull complete
52a0e0497fc8: Pull complete
f5d1eb084ee1: Pull complete
6c5b56366cbd: Pull complete
ae5bd075f2e2: Pull complete
aedeecd18e7a: Pull complete
3f79f3f9be61: Pull complete
4a76ac53c9fb: Pull complete
1356b01905df: Pull complete
Digest: sha256:bd08993bec0cb51aac002142f18a58b7eb0cb13e36ae44505e1cab22a5f156f5
Status: Downloaded newer image for registry.hub.docker.com/psafont/ebitools:20170602
```

I've installed `dx-docker` with `pip install dxpy`, maybe there's something else I need to install? I didn't see clear instructions on other dependencies.

**Comment by geetduggal** [comment]
Hmm interesting.  Could you provide more details about your environment as I was able to run that command successfully:

![image](https://user-images.githubusercontent.com/64425/32465574-cd8303c0-c2f8-11e7-8c89-66882c68d34f.png)

Also, if you're not already aware, you may be interested in some integrations we have contributed to cwltool that allows using dx-docker or other user-space docker implementation: 

https://github.com/common-workflow-language/cwltool/commit/1f2dbf0c972a0ad9546fd614a386e71817ae5929

Also, we are actively working on the capability to compile CWL workflows to DNAnexus. Though it is in a highly alpha stage, we are able to successfully run a variety of CWL workflows and are working on improving it and building documentation for best practices soon:

https://github.com/dnanexus/dx-cwl

If this is something that interests you, feel free to continue the discussion with me (email: gduggal@dnanexus.com).

**Comment by psafont** [comment]
I'm running dx-docker in a python 2.7.14 environment, under Linux.

```
$ pip freeze
avro==1.8.1
beautifulsoup4==4.4.1
CacheControl==0.11.7
certifi==2017.11.5
chardet==3.0.4
cwltool==1.0.20171017195544
dxpy==0.225.0
fusepy==2.0.2
futures==3.0.4
idna==2.6
isodate==0.6.0
lockfile==0.12.2
mistune==0.7.4
psutil==3.3.0
pyparsing==2.2.0
python-dateutil==2.3
python-magic==0.4.6
rdflib==4.2.2
rdflib-jsonld==0.4.0
requests==2.7.0
ruamel.ordereddict==0.4.13
ruamel.yaml==0.14.12
schema-salad==2.6.20171102064032
shellescape==3.4.1
six==1.11.0
typing==3.6.2
urllib3==1.22
ws4py==0.3.2
xattr==0.6.4
```

Is there anything you want to know about the environment, specifically?

**Comment by psafont** [comment]
I've been debugging the code and here's the actual exception that triggers the error:

```
Traceback (most recent call last):
  File "<pudb command line>", line 1, in <module>
  File "/home/psafont/.config/virtualenvs/cwl/bin/dx-docker", line 103, in docker2aci_line
    popen = subprocess.Popen(cmd, stderr=subprocess.PIPE, stdout=open(os.devnull, "w"), universal_newlines=True)
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

The problems was that I did not have docker2aci installed.
Some documentation about it in the python readme would be nice :)

**Comment by geetduggal** [comment]
Thanks for the info!  I think this is a discrepancy between our pip installer vs. the binaries we distribute on our wiki: https://wiki.dnanexus.com/Downloads as that and our apt repository ones work.   Thanks for pointing this out and we'll look into it.
