### ISSUE TITLE
Update dxpy in PIP

### ISSUE THREAD

**Issue by claymcleod** [dnanexus/dx-toolkit#279]
Hi DNAnexus,

Looks like the latest version of dxpy is v0.225. Wondering if we can keep the version of `dxpy` in PIP up to date with the releases (especially with what's released here: https://wiki.dnanexus.com/Downloads#DNAnexus-Platform-SDK).

```bash
# cmcleod at L180083 in venv [14:42:37]
➜  pip search dxpy
dxl-dxpy (0.6.3)  - Duplicate components library python sub-library.
dxpy (0.225.0)    - DNAnexus Platform API bindings for Python
gdxpy (0.1.3)     - Manipulate GAMS GDX files as Pandas data structures for convenient computation and visualization
sdxpys (1.0.1)    - this is a test package for packing python liberaries tutorial.

# cmcleod at L180083 in venv [14:42:22]
➜  pip show dxpy
Name: dxpy
Version: 0.225.0
Summary: DNAnexus Platform API bindings for Python
Home-page: https://github.com/dnanexus/dx-toolkit
Author: Katherine Lai, Phil Sung, Andrey Kislyuk, Anurag Biyani
Author-email: expert-dev@dnanexus.com
License: Apache Software License
Location: /Users/cmcleod/.sjcloud/venv/lib/python2.7/site-packages
Requires: psutil, ws4py, beautifulsoup4, requests, fusepy, xattr, python-magic, gnureadline, futures, python-dateutil
```

**Comment by claymcleod** [comment]
After looking at this a little closer, it looks like the error I originally described is actually caused by Python 2.7.14 not being correctly configured with `openssl`. I'll still keep this issue here as a suggestion to keep PIP up to date.

At this point, the whole TLS 1.2 and Python2 issue is becoming a sticking point for many of our users. Wondering if you guys have reconsidered bumping the supported version of Python up to 3 to resolve all of these issues?

**Comment by kpjensen** [comment]
Hi Clay, thanks for letting us know. I updated pypi with the latest stable release for now. Once I incorporate this into our regular build and release process I will close this issue.
```
kjensen-mv-ltmp-x:~ kjensen$ pip show dxpy
Name: dxpy
Version: 0.240.1
Summary: DNAnexus Platform API bindings for Python
Home-page: https://github.com/dnanexus/dx-toolkit
Author: Katherine Lai, Phil Sung, Andrey Kislyuk, Anurag Biyani
Author-email: expert-dev@dnanexus.com
License: Apache Software License
Location: /usr/local/lib/python2.7/site-packages
Requires: fusepy, xattr, futures, python-magic, python-dateutil, ws4py, beautifulsoup4, psutil, requests
```

**Comment by claymcleod** [comment]
Thank you!
