### ISSUE TITLE
ERROR: Building Apps

### ISSUE THREAD

**Issue by xogur** [dnanexus/dx-toolkit#282]
I am trying to build an applet on the cloud as a test. I am following the procedure of the 'Developer Tutorials/Intro to Building Apps' with the 'fastq_quality_trimmer' (https://wiki.dnanexus.com/Developer-Tutorials/Intro-to-Building-Apps). But, in the step of the 'dx build mytrimmer', I have gotten an error at below.

$ dx build mytrimmer
Error: destination project is in region azure:westus but "regionalOptions" do not contain this region. Please, update your "regionalOptions" specification

Could you please help me to figure it out? 

Thank you!

**Comment by kpjensen** [comment]
Hello,

The `dx-app-wizard` by default generates a `dxapp.json` file with  only `aws:us-east-1` as the region under `regionalOptions`. The project you are building this applet in resides in `azure:westus` region, if you swap them in `dxapp.json` the applet should build. 

Below is an example with the azure region, let me know if that works for you.  

```
"regionalOptions": {
    "azure:westus": {
      "systemRequirements": {
        "*": {
          "instanceType": "mem1_ssd1_x4"
        }
      }
    }
  }
```

**Comment by xogur** [comment]
Thank you for your comment!

I have changed the regional option. But, another error have come up. 

$ dx build mytrimmer
Error: The instance type specified for stage "*" is not a recognized instance type, code 422. Request Time=1513295211.91, Request ID=1513295211296-560110

I attached my json file.

{
  "name": "mytrimmer",
  "title": "mytrimmer",
  "summary": "mytrimmer",
  "dxapi": "1.0.0",
  "version": "0.0.1",
  "inputSpec": [
    {
      "name": "input_file",
      "class": "file",
      "optional": false,
      "patterns": [
        "*"
      ],
      "help": ""
    }
  ],
  "outputSpec": [
    {
      "name": "output_file",
      "class": "file",
      "patterns": [
        "*"
      ],
      "help": ""
    }
  ],
  "runSpec": {
    "timeoutPolicy": {
      "*": {
        "hours": 48
      }
    },
    "interpreter": "bash",
    "release": "14.04",
    "distribution": "Ubuntu",
    "file": "src/mytrimmer.sh"
  },
  "access": {
    "network": [
      "*"
    ]
  },
  "regionalOptions": {
    "azure:westus": {
      "systemRequirements": {
        "*": {
          "instanceType": "mem1_ssd1_x4"
        }
      }
    }
  }
}

**Comment by kpjensen** [comment]
Sorry about that, one more azure prefix for you. For `instanceType` the cloud provider for the region is a prefix as well, e.g.`azure:mem1_ssd1`.
We filed an internal ticket as well to update the developer tutorial with azure information.

**Comment by xogur** [comment]
Thank you  for your help!
