### ISSUE TITLE
Error building from source: tar cannot create symlink

### ISSUE THREAD

**Issue by alizrrao** [dnanexus/dx-toolkit#284]
I'm getting an error when trying to build from source. I'm running Ubuntu 16.04.3 within Virtualbox.

```
$ tar -xzvf dx-toolkit-v0.241.0-source.tar.gz
dx-toolkit/
dx-toolkit/.arcconfig
dx-toolkit/.arclint
dx-toolkit/.gitignore
...
tar: dx-toolkit/src/jq/README: Cannot create symlink to ‘README.md’: Read-only file system
...
tar: dx-toolkit/doc/example-templates: Cannot create symlink to ‘../src/python/dxpy/templating/templates’: Read-only file system
tar: Exiting with failure status due to previous errors
```
Later, trying to run make anyway:

```
$ make
...
mkdir -p "$(dirname '/media/sf_Documents/Programs_Installers/linux.x86_64/dx-toolkit/src/../share/dnanexus/lib/python2.7/site-packages')"
virtualenv --python=python "/media/sf_Documents/Programs_Installers/linux.x86_64/dx-toolkit/src/../build/py_env"
/bin/bash: virtualenv: command not found
Makefile:171: recipe for target '/media/sf_Documents/Programs_Installers/linux.x86_64/dx-toolkit/src/../bin/dx' failed
make[1]: *** [/media/sf_Documents/Programs_Installers/linux.x86_64/dx-toolkit/src/../bin/dx] Error 127
make[1]: Leaving directory '/media/sf_Documents/Programs_Installers/linux.x86_64/dx-toolkit/src'
Makefile:18: recipe for target 'all' failed
make: *** [all] Error 2
```
Any suggestions on what I could try?

**Comment by geetduggal** [comment]
Interesting.  I have not seen that error before myself, but as a first shot in the dark, are you working in a file system that may not allow sym links (e.g. https://github.com/hashicorp/vagrant/issues/713)?

**Comment by alizrrao** [comment]
That must be it, thanks! In the meantime, I was able to install the SDK
from the repository, by installing the version meant for Ubuntu 14.04. It
seems to work fine, even though I'm using Ubuntu 16.04.

**Comment by geetduggal** [comment]
Great to hear!  Closing the issue. 

P.S. Yes, we've noticed the same thing that the toolkit works on 16.04 without any apparent issue thus far.  We are currently finishing up development to flexibly allow for other releases including 16.04 and will provide official toolkit releases compatible with 16.04 after.
