### ISSUE TITLE
dx unset all properties?

### ISSUE THREAD

**Issue by claymcleod** [dnanexus/dx-toolkit#289]
Hi DNAnexus,

I've used the `dx unset_properties` function, but it seems like it requires you to know which property name you'd like to unset. Is there a way to remove _all_ of the properties on an object? This would really help me out.

Thank you!

**Comment by commandlinegirl** [comment]
Hello! Thank you for the suggestion, I created a ticket for that and we'll try to tackle it when we find a spare moment. In the meantime you can `dx describe --json` an object, get the names of the properties and remove them with`dx unset_properties`. Best, Ola

**Comment by commandlinegirl** [comment]
Hi Clay, it's not yet implemented. I was cleaning the `issues` yesterday and closed it accidentally. Will reopen.
