### ISSUE TITLE
dx get fails if no execDepends

### ISSUE THREAD

**Issue by notestaff** [dnanexus/dx-toolkit#314]
at https://github.com/dnanexus/dx-toolkit/blob/master/src/python/dxpy/utils/executable_unbuilder.py#L224
should maybe be
if dx_toolkit in dxapp_json["runSpec"].get("execDepends", ()):

**Comment by commandlinegirl** [comment]
Hi Ilya, thank you for bringing it to our attention! I'll look into it.

Best,
Ola

**Comment by commandlinegirl** [comment]
The fix landed in master, thanks!
