### ISSUE TITLE
streaming data between stages

### ISSUE THREAD

**Issue by notestaff** [dnanexus/dx-toolkit#317]
If one could stream data between workflow stages, stages that now run in sequence could run in parallel.  User would designate some app(let) inputs  and outputs as "streamable", meaning they can be a named pipe, and then you could run two stages in parallel on one worker instance, streaming data from one to the other.   (Or even on different instances, streaming through a socket.)  To work with the current API, you could take a workflow and automatically combine two or more stages into one, if the corresponding inputs and outputs are streamable.

**Comment by orodeh** [comment]
This is a complex problem, and we don't have a general solution for this right now. dxfs was one attempt to do this, but we ended up deciding it was not the right way to go.
