### ISSUE TITLE
Problems with dx logout

### ISSUE THREAD

**Issue by pkaleta** [dnanexus/dx-toolkit#436]
@orodeh 

I'm getting this when calling `dx logout` from the command line:

```
% dx logout
Deleting credentials from https://auth.dnanexus.com...
Traceback (most recent call last):
  File "/Users/piotr/counsyl/myelin-state-machines/.venv/lib/python3.6/site-packages/dxpy/scripts/dx.py", line 418, in logout
    token_sig = hashlib.sha256(token).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

I'm using `dx v0.267.0`

**Comment by orodeh** [comment]
Thanks. Branch https://github.com/dnanexus/dx-toolkit/tree/orodeh_python_23 fixes this bug. It is a branch that works on both python 2 and 3, and is in the process of being merged back into master.

**Comment by pkaleta** [comment]
Thanks for a quick response.
