### ISSUE TITLE
Check cache for dx-docker pull

### ISSUE THREAD

**Issue by ying-w** [dnanexus/dx-toolkit#460]
I recently ran into an issue when running `dx-docker run` where image is cached in `/tmp/dx-docker-cache`. It was confusing for me to see that `run` would work but `pull` would not

It would also be nice if you guys changed the call to shell in `extract_aci()` from `shell_suppress()` to `shell()` or to throw some error when it fails at that step. 

By default the *aci files in `/tmp/dx-docker-cache` do not have read permissions for dnanexus user and will fail with error about missing manifest which is not very informative

**Comment by jtratner** [comment]
Explanatory note - we have to use dx-docker right now because dxWDL does not support native docker tarballs. Once there is native docker support in dxWDL, we would no longer care about dx-docker and this ticket would not be an issue for us ;)
