### ISSUE TITLE
Support dxWDL "natively" via docker

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dx-toolkit#462]
It'd be super sweet to get dxWDL support in a standard way through dx toolkit.

For example, a small shell script like this would be a very nice way to wrap this up

(call it `dxwdl`)

```
#!/bin/bash
eval "$(dx env --bash)"
docker run -e DX_SECURITY_CONTEXT -v $PWD:$PWD some-image-with-dxWDL:0.78.1 "$@"
```

Then can do
```
dxwdl compile ...
```

etc - with no java required! magic!

**Comment by orodeh** [comment]
This is implemented in the dxWDL repository (https://github.com/dnanexus/dxWDL/blob/master/scripts/compiler_image/run-dxwdl-docker)
