### ISSUE TITLE
dx-docker losing backslashes

### ISSUE THREAD

**Issue by multimeric** [dnanexus/dx-toolkit#464]
I have a bwa aligner image, which I invoke in DNAnexus using:
`['dx-docker', 'run', '-v', '/home/dnanexus/in:/app/in', '-v', '/home/dnanexus/out:/app/out', 'bwa_mem', '--reference', '/app/in/ucsc.hg19.fasta.gz', '--output', '/app/out/NTC-001.bam', '--read_1', '/app/in/TEST_NTC-001_batch01_SSQXTCRE_L001_R1.fastq.gz', '--read_2', '/app/in/TEST_NTC-001_batch01_SSQXTCRE_L001_R2.fastq.gz', '--read-group', '@RG\\tID:NTC-001\\tPL:ILLUMINA\\tPU:1\\tLB:Unknown\\tSM:NTC-001']`

So at this point, it is obvious that I'm escaping the backslashes in the read group (I want the literal characters `\t`, _not_ the tab character between the sections of the read group)

However, the first line of the `bwa_mem` script (which is written in Python) is:
```python
import sys
print("Raw args are: " + ' '.join(sys.argv))
```
And this outputs:
```
Raw args are: ./align.py --reference /app/in/ucsc.hg19.fasta.gz --output /app/out/NTC-001.bam --read_1 /app/in/TEST_NTC-001_batch01_SSQXTCRE_L001_R1.fastq.gz --read_2 /app/in/TEST_NTC-001_batch01_SSQXTCRE_L001_R2.fastq.gz --read-group @RGtID:NTC-001tPL:ILLUMINAtPU:1tLB:UnknowntSM:NTC-001
```

Thus, it looks like `dx-docker` is consuming my backslashes, which I obviously need. This doesn't seem to happen in normal docker, because my testing framework runs using `docker`, and also with `dx-docker` in DNAnexus.

**Comment by kpjensen** [comment]
Thanks for reporting. There have been many issues with `dx-docker` related to this.

Is it possible for you change the Ubuntu release of your DNAnexus applet to Ubuntu 16.04? We support native `docker` in this environment. `docker-ce` is pre-installed in this environment.
https://wiki.dnanexus.com/Developer-Tutorials/Using-Docker-Images

**Comment by commandlinegirl** [comment]
`dx-docker` has been deprecated. Please use docker instead.
