### ISSUE TITLE
0.274.0 not on pypi?

### ISSUE THREAD

**Issue by notestaff** [dnanexus/dx-toolkit#468]
Latest version on github in 0.274.0 , but on pypi it's 0.273.0 .

**Comment by commandlinegirl** [comment]
v0.274.0, available from github, is a beta version, not on pypi yet. v0.273.0 is the last stable version. The next release is planned for Thursday, it will push 0.274.0 to pypi.

**Comment by notestaff** [comment]
thanks.  CHANGELOG says 0.273.0 is beta and 0.272.0 is stable, I guess that's outdated?

**Comment by commandlinegirl** [comment]
You're right, I updated it. Thanks
