### ISSUE TITLE
aria2c raising exception when running `dx download` on large files using instance type with 32 cores

### ISSUE THREAD

**Issue by acchiao** [dnanexus/dx-toolkit#472]
When running `dx download` on large (~100 GB) files onto an instance with 32 cores using the `aria2c` downloader, it will raise an exception.

```
+ dx download '{"$dnanexus_link": "file-<redacted>"}' -o input
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--max-connection-per-server'.
  -> [OptionHandlerImpl.cc:187] errorCode=1 max-connection-per-server must be between 1 and 16.
Usage:
 -x, --max-connection-per-server=NUM The maximum number of connections to one
                              server for each download.
                              Possible Values: 1-16
                              Default: 1
                              Tags: #basic, #http, #ftp
Traceback (most recent call last):
  File "/usr/share/dnanexus/lib/python2.7/site-packages/dxpy/bindings/dxfile_functions.py", line 195, in _download_symbolic_link
    subprocess.check_call(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '[u'aria2c', u'--check-certificate=false', u'-s', '32', u'-x', '32', u'-o', u'input', u'-d', u'/', u'http://<redacted>']' returned non-zero exit status 28
Failed to call download: [u'aria2c', u'--check-certificate=false', u'-s', '32', u'-x', '32', u'-o', u'input', u'-d', u'/', u'http://<redacted>']
```

This is due to `aria2c` having a [hard coded limit of 16 possible connections](https://github.com/aria2/aria2/blob/8985d66e71f980e7d2765753800078f47761f1ba/src/OptionHandlerFactory.cc#L422) for a server. See issue [here](https://github.com/aria2/aria2/issues/580). It has been deemed a non-issue ([#648](https://github.com/aria2/aria2/pull/648#issuecomment-217971648)), but it is possible to edit the value and recompile ([#729](https://github.com/aria2/aria2/issues/729#issuecomment-242366689)).

The `--split` also seems to be restricted by the `--max-connection-per-server` option. See [here](https://aria2.github.io/manual/en/html/aria2c.html?highlight=split#cmdoption-s).

---

The line below causes `aria2c` to exceed the max limit of 16 connections when using an instance with 32 cores.

https://github.com/dnanexus/dx-toolkit/blob/4af27c9b87055382cc44b456b5e23333c70224b4/src/python/dxpy/bindings/dxfile_functions.py#L187

Running the same script (same inputs and files being downloaded) but only changing the instance type to one with 16 cores seems to work just fine. For reference, the exception is being thrown when using `"instanceType": "azure:mem4_ssd1_x32"` in my `dxapp.json` file.

Changing to `"instanceType": "azure:mem4_ssd1_x16"` downloads and runs properly.

**Comment by kpjensen** [comment]
Thanks for reporting this. Added a max of 16 for the `aria2c` call so symlink downloads will work on instances with > 16 cores.
