### ISSUE TITLE
dx download raises exception when run with -o flag

### ISSUE THREAD

**Issue by acchiao** [dnanexus/dx-toolkit#481]
When running `dx download "$input" -o input`, specifically with the `-o input` flag, `md5sum` will raise an exception.

**Issue:**
It seems that `md5sum` will check if `input` is in the root directory (`md5sum -b /input`), but the file is actually downloaded to the home directory (`/home/dnanexus/input`) and it should be checking whether the file exists in the home directory. When `md5sum` is run on a download with the `-o` flag, it will raise an exception because it can't find the file and terminate.

https://github.com/dnanexus/dx-toolkit/blob/8b3421f013b1df4c201e0c2a753f4f8886c366e4/src/python/dxpy/bindings/dxfile_functions.py#L146

https://github.com/dnanexus/dx-toolkit/blob/8b3421f013b1df4c201e0c2a753f4f8886c366e4/src/python/dxpy/bindings/dxfile_functions.py#L149

Please see attached log file.
 

- [dx-download.log](https://github.com/dnanexus/dx-toolkit/files/2847423/dx-download.log)

**Comment by orodeh** [comment]
This is fixed in dx version 0.276. Please reopen if it still does not work for you there. 

Thank you.
