### ISSUE TITLE
dx watch --color on doesn't seem to work

### ISSUE THREAD

**Issue by Lenbok** [dnanexus/dx-toolkit#542]
I want to pipe the output of `dx watch` into `less -R` to view the log output, with colors, however the colors are disabled, even when I use `--color on` to force them to be on.

I'm using DNAnexus Command-Line Client, API v1.0.0, client v0.285.1

**Comment by orodeh** [comment]
I don't think this is a problem with `dx watch`, because it is displaying the colors correctly.

**Comment by Lenbok** [comment]
Can you pipe the output of `dx watch --color on job_id | less -R` and see the colors? It doesn't work for me.

Similarly, if I run `dx watch --color on job_id | hexdump -C` I don't see escape codes in the output.

Any suggestions?

**Comment by orodeh** [comment]
How about this: 
```
dx watch job-<hash> --color=on | less -r
```

**Comment by Lenbok** [comment]
Nope, doesn't work for me (and note what I said about the control characters not appearing in the hexdump, so no less was involved). Please reopen, as this has not been resolved.

**Comment by orodeh** [comment]
Regarding less, this solution works on my bash terminal. So, I suspect this is a matter of your bash settings. 

Another tack is to do something like this: https://unix.stackexchange.com/questions/151666/how-do-i-preserve-coloured-output-when-piping-to-less-r

**Comment by Lenbok** [comment]
OK, something is weird, and it looks to be related to the python on my system. 

I'm using Ubuntu 18.04.2 LTS. If I use the default system python ("Python 2.7.15+", I get the problems I describe above. However, if I create a virtualenv (using the same system python interpreter), and activate it, the color handling works as it should. 

At least I have a workaround now, and I'm not sure there's anything you can do if you can't reproduce it. Thanks for the help.
