### ISSUE TITLE
dx watch to retrieve logs for completed job

### ISSUE THREAD

**Issue by Lenbok** [dnanexus/dx-toolkit#543]
I have completed jobs that I want to retrieve the logs for. `dx watch` seems to the only way of retrieving the logs from the command line, but it always hangs around waiting for Ctrl-C to terminate instead of returning to the command prompt. I initially thought that `--no-follow` or `--no-wait` would do what I want, but nope. Is there a way to tell `dx watch` not to wait (or another method to script the log retrieval?)

BTW, the web UI job log browser works terribly under Firefox (which is what has made me come to the command line for my log viewing), in case you want to pass that on to your testers.

**Comment by orodeh** [comment]
@Lenbok, `dx watch` is just a bit slow when closing the stream. It should close with a message that looks like this: 
```
* <applet-name> (sort_file:main) (done) job-<hash>
  <user-id> 2019-07-10 13:38:09 (runtime 0:00:27)
  Output: outf_sorted = file-<hash>
          outf = file-<hash>
```

after a while. Regarding the web-UI, I will pass that on. Thanks for reporting.

**Comment by Lenbok** [comment]
Rightyo, seems I was just too impatient :-)

**Comment by sclan** [comment]
Deployment of the improvement to reduce the wait period from `dx watch job-xxxx` is scheduled to be mid February. Closing.
