### ISSUE TITLE
Incorrect username and/or password

### ISSUE THREAD

**Issue by adily777** [dnanexus/dx-toolkit#578]
Hello,

I do `dx login` from command line (linux) with the **correct** username and password but get: 
`Incorrect username and/or password`

When I put them on the site it succeeded.

What can I do?
Adily

**Comment by adily777** [comment]
When I do dx login I get:
Acquiring credentials from https://stagingauth.dnanexus.com instead of https://auth.dnanexus.com

Why is that?

Thank you,
Adily

**Comment by commandlinegirl** [comment]
Hi Adily,

It seems your environment is set to log in to our staging environment instead of production (you can verify it by running `dx env`). To be able to log to prod, run `dx clearenv` and try to login again.

HTH
Ola

**Comment by adily777** [comment]
Thanks a lot! It works!

**Comment by commandlinegirl** [comment]
Great!:-)
