### ISSUE TITLE
Python Cryptography dependency<=2.2.2

### ISSUE THREAD

**Issue by NickEngland** [dnanexus/dx-toolkit#615]
Hi,

I'm trying to use dxpy on Amazon Linux, and I can't get pip to install a version of cryptography which is version 2.2.2 or earlier. Is there a reason that later versions such as 2.9.2 won't work?

**Comment by caaespin** [comment]
Also wondering this

**Comment by kpjensen** [comment]
This dependency will be upgraded in an upcoming release after https://github.com/dnanexus/dx-toolkit/pull/626 is merged.
If you need to install it sooner you direct pip to that branch for now.
```
pip install -U "git+https://github.com/dnanexus/dx-toolkit.git@DEVEX-1723#egg=dxpy&subdirectory=src/python"
```

**Comment by kpjensen** [comment]
Updated in stable release `v0.297.1`.
