### ISSUE TITLE
Incorrect PYTHONPATH set for RHEL 7

### ISSUE THREAD

**Issue by jethror1** [dnanexus/dx-toolkit#671]
When trying to use `dx` following sourcing the toolkit on RHEL 7 it gives the following error:

```
Traceback (most recent call last):
  File "/opt/dx-toolkit/bin/dx", line 6, in <module>
    from dxpy.scripts.dx import main
ImportError: No module named dxpy.scripts.dx
```

In the `environment` script in the toolkit the following is set for PYTHONPATH:

```
  if [ "$RHEL_MAJOR_VERSION" = "7" ]; then
    export PYTHONPATH="${DNANEXUS_HOME}/share/dnanexus/lib64/${PYTHON_VERSION}/site-packages:$PYTHONPATH"
  else
    export PYTHONPATH="${DNANEXUS_HOME}/share/dnanexus/lib/${PYTHON_VERSION}/site-packages:$PYTHONPATH"
  fi
```

This does not appear to be correct as the same tar is distributed for all versions of RHEL, yet the path for RHEL 7 is set to `lib64` instead of `lib`. The full dir path in the extracted tar to the python site packages is `/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/`.

Removing the `64` from the path and re-sourcing seems to fix the issue and allow for using the toolkit, so this if else for the export seems to be incorrect.

**Comment by emiloslavsky** [comment]
does the same problem occur when you `pip3 install dxpy`?

**Comment by jethror1** [comment]
apologies for the delay in replying, we have now migrated away from RHEL 7 since it is coming to EOL at the end of this month. On RHEL 9 we have switched to installing from dxpy since using the toolkit source also did not work (but with different errors). Since RHEL 7 is EOL you can probably consider this not worth fixing and can be closed.

**Comment by emiloslavsky** [comment]
Thanks @jethror1 !

**Comment by emiloslavsky** [comment]
closing
