### ISSUE TITLE
Do not depend on gnureadline

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dx-toolkit#676]
`gnureadline` is an optional dependency anyways, and only used for a subset of dxpy commands.  It's annoying to get `gnureadline` installed on certain machines, so it'd be nice to remove the dependency. (can always include it in the toolkit download).

**Comment by emiloslavsky** [comment]
internally tracked as DEVEX-2259

**Comment by wormsik** [comment]
Hi @jtratner, we were able to fully remove `gnureadline` dependency for all the operating systems and python versions (#1016). This change will be released in an upcoming release of dx-toolkit.

**Comment by jtratner** [comment]
Amazing! Glad we could finally eliminate this dependency!
