### ISSUE TITLE
The cloud workstation app defaults to Ubuntu 16.04 

### ISSUE THREAD

**Issue by Graeme-Smith** [dnanexus/dx-toolkit#681]
When running an interactive workstation using the app-cloud_workstation it would be useful to be able to specify the version of Ubuntu used (currently only 16.04 is supported and this version has reached the end of life and will no longer receive maintenance updates).  I'm trying to update some of our legacy apps from using  16.04 to 20.04 and it would be useful to have an interactive environment I could test dependencies in.

**Comment by emiloslavsky** [comment]
Ubuntu version is the property of the app itself, not of dx-toolkit.
We will be transitioning cloud_workstation to 20.04 in the coming quarter.
In the meantime, you can build an 20.04 cloudworkstation applet by 
- `dx get cloud_workstation && cd cloud_workstation`
-  modify dxapp.json to use Ubuntu 20.04, version "0" , remove ipython execdepends package
- ` dx build .`
