### ISSUE TITLE
dx upload fails on large (~100MB) files

### ISSUE THREAD

**Issue by dcaldhr** [dnanexus/dx-toolkit#710]
Running on the latest MacOS (11.3.2), I am unable to upload large files. At least, an error stating the limitation would be printed. Ideally, the command would support larger uploads. (Upload Agent currently doesn't work on MacOS either.)

```
dx upload file.csv --destination /data/
WARNING:dxpy:[Thu Aug  5 09:09:39 2021] PUT https://dnanexus-platform-upload-prod.s3.amazonaws.com/filev2/... urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out')). Waiting 1 seconds before retry 1 of 6... 
WARNING:dxpy:[Thu Aug  5 09:09:39 2021] PUT https://dnanexus-platform-upload-prod.s3.amazonaws.com/filev2/... urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out')). Waiting 1 seconds before retry 1 of 6... 
...
WARNING:dxpy:[Thu Aug  5 09:20:00 2021] PUT https://dnanexus-platform-upload-prod.s3.amazonaws.com/filev2/... urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe')). Waiting 8 seconds before retry 4 of 6...
...
```

**Comment by kpjensen** [comment]
Can you try adding the following parameters to see if it helps? This will upload the file in 5MiB parts sequentially. 
```
dx upload --singlethread --buffer-size 5242880
```
By default `dx-toolkit` will upload 16MiB parts in parallel, which may be timing out on your connection.

**Comment by dcaldhr** [comment]
Thank you, @kpjensen, those parameters allowed the upload to complete without error. For the record, my uplink in this example is in the range 5-10Mbps.
