### ISSUE TITLE
DXDataObject describe with field properties return error

### ISSUE THREAD

**Issue by JasonLing95** [dnanexus/dx-toolkit#735]
`project.describe(fields={'properties'}, default_fields=True)` returns `TypeError: request got values for both 'fields' and 'body', can only specify one.`. It works for `DXFile` but return this error on `DXProject`

**Comment by kpjensen** [comment]
`DXProject` inherits from `DXObject`, not `DXDataobject`. You can call its `describe()` function with the raw api parameters.
If you only want to retrieve the project's properties you can call it like below: 
```
project.describe(input_params={'fields':{'properties':True}})
```
