### ISSUE TITLE
dx-app-wizard crashes with --json-file that lacks "optional" key

### ISSUE THREAD

**Issue by kyclark** [dnanexus/dx-toolkit#761]
I am trying to create a new "fastqc" app using the existing "dxapp.json" from the current version of the app (https://github.com/dnanexus/file-apps/blob/master/apps/fastqc/dxapp.json). Just after setting the version, the program crashes with the following message:

```
Traceback (most recent call last):
  File "/Users/kyclark@dnanexus.com/.local/bin/dx-app-wizard", line 33, in <module>
    sys.exit(load_entry_point('dxpy==0.318.1', 'console_scripts', 'dx-app-wizard')())
  File "/Users/kyclark@dnanexus.com/.local/lib/python3.9/site-packages/dxpy/scripts/dx_app_wizard.py", line 275, in main
    may_be_missing = param['optional'] and "default" not in param
KeyError: 'optional'
```

The "optional" key must be missing from the "param" dict and so raises the KeyError. Recommend to replace with "dict.get()" method.

**Comment by kpjensen** [comment]
Released in v0.321.0
