### ISSUE TITLE
dxpy.exceptions.DXCLIError: Value provided for input field "in" could not be parsed as file:

### ISSUE THREAD

**Issue by monika3010** [dnanexus/dx-toolkit#802]
Hello, I'm trying to run a test script via the CLI.

I typed the following into the CLI 
dx run swiss-army-knife -iin="AUGMENT:/Analysis/scripts/test_script.sh" -icmd="bash test_script.sh"

my test_script.sh is as follows 
!/bin/bash

dx run app-swiss-army-knife \
-iin="/mnt/project/Bulk/Genotype\ Results/Genotype\ calls/ukb22418_c16_b0_v2" \
-icmd='plink --bfile "ukb22418_c16_b0_v2" --freq --out AUGMENT:/Analysis/outputs/chr16_maf' \
--instance-type="mem1_ssd1_v2_x16" \
-y

I get the following error
**dxpy.exceptions.DXCLIError: Value provided for input field "in" could not be parsed as file: could not resolve "/mnt/project/Bulk/Genotype\ Results/Genotype\ calls/ukb22418_c16_b0_v2" to a name or ID**

I also tried amending the path
-iin="/mnt/project/Bulk/Genotype Results/Genotype calls/ukb22418_c16_b0_v2" \

but I'm getting the same error.

**Comment by commandlinegirl** [comment]
Hi @monika3010!

The input type passed to `in` in your script running the swiss-army-knife app should be a file or an array of files, not a string. If you want to use the mounted file in your cmd you can pass something like: `dx run ... -icmd="plink --bfile /mnt/project/Bulk/Genotype\ Results/Genotype\ calls/ukb22418_c16_b0_v2"` (the project contents will already have been mounted when you run this command). 

HTH!

**Comment by monika3010** [comment]
Thank you @commandlinegirl, it worked.
